version: '3.4'

services:
  db:
    env_file:
      - .env
    image: mariadb:10.3
    networks:
      - nginx-proxy
    restart: always
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - wordpress
    env_file:
      - .env
    environment:
      - LETSENCRYPT_HOST=${SITE_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${SITE_LETSENCRYPT_EMAIL}
      - VIRTUAL_HOST=${SITE_VIRTUAL_HOST}
    image: nginx:1.13-alpine
    networks:
      - nginx-proxy
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/wordpress.template:/etc/nginx/conf.d/wordpress.template
  wordpress:
    depends_on:
      - db
    env_file:
      - .env
    image: wordpress:4.9-fpm-alpine
    networks:
      - nginx-proxy
    restart: always
    volumes:
      - ./docker/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

networks:
  nginx-proxy:
    external: true

volumes:
  db_data:
